server:
  port: 9002
spring:
  application:
    name: hrm-course
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3006/hrm_sysmanage
      username: root
      password: 942255
mybatis-plus:
  mapper-locations: classpath:com/wgb/hrm/mapper/*Mapper.xml
  type-aliases-package: com.wgb.hrm.domain,com.wgb.hrm.query